baseURL = 'https://straumat.github.io/second-cerveau/'
landingPageURL = '/second-cerveau'
languageCode = 'fr-FR'
title = 'Second cerveau'
theme = 'hugo-theme-learn'

[params]
themeVariant = "blue"


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

