baseURL = 'https://straumat.github.io/second-cerveau/'
IsMultiLingual = false
landingPageURL = '/second-cerveau'
languageCode = 'fr-FR'
title = 'Second cerveau'
theme = 'hugo-theme-learn'

[params]
themeVariant = "blue"
landingPageURL = '/second-cerveau'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]