name: On push, publish the new website

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ================================================================================================================
      - name: Retrieve the sources
        uses: actions/checkout@v3

      # ================================================================================================================
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.106.0'
          extended: true

      # ================================================================================================================
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ================================================================================================================
      - name: Npm install
        run: npm install

      # ================================================================================================================
      - name: Build Hugo website in the beta directory
        run: |
          hugo version
          hugo --minify --gc 

      # ================================================================================================================
      - name: Deploy the website to github pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: public
          commit-message: "Website deployment"
          clean: true